## Конфигурация

In [5]:
import asyncio
import json
from pathlib import Path
from tqdm import tqdm
from typing import Tuple, Set, Dict

import polars as pl
from openai import AsyncOpenAI

CATEGORY = "Pet_Supplies"
DATA_DIR = Path.cwd()
CHECKPOINT_PATH = "checkpoint/clean_description_and_title.jsonl"
OUTPUT_PATH = f"prepared/{CATEGORY}_items_cleaned.parquet"
INPUT_PATH = f"prepared/{CATEGORY}_items.parquet"

MAX_TITLE_LEN = 200
MAX_DESC_LEN = 2000
MAX_FEATURES_LEN = 2000

OPENROUTER_API_KEY = __import__('os').environ['OPENROUTER_API_KEY']
MODEL = "google/gemini-2.5-flash-lite"
CONCURRENCY = 50

client = AsyncOpenAI(
    api_key=OPENROUTER_API_KEY,
    base_url="https://openrouter.ai/api/v1",
)

## Промпт

In [6]:
SYSTEM_PROMPT = """You normalize e-commerce product metadata. Not a copywriter.

Return STRICT JSON:
{"clean_title": string, "clean_description": string, "clean_features": [string]}

Rules:
- Use ONLY facts present in the input. Do NOT add, infer, generalize, or invent anything.
- Preserve all numbers, units, sizes, materials, limits, warranty, country of origin, and brand names.
- Fix grammar, spelling, punctuation.
- Remove HTML, entities, emojis/checkmarks, duplicate words/phrases, formatting noise, ALL CAPS shouting.
- If text ends with "...", complete ONLY from existing context.

Title:
- Remove promo noise (NEW, SALE, LIMITED, etc.).
- Remove seller/store/platform tags.
- Use Title Case.
- Keep brand, model, key specs.

Description:
- Keep all factual info.
- Under 200 words.
- Convert lists/bullets into fluent sentences.

Features:
- Output 3–12 concise bullets when possible.
- Each bullet should be factual and short (3–18 words if possible).
- Remove non-factual marketing fluff (e.g., “best”, “perfect”, “leader”, “focus of the scene”, “after-sales service”)
  unless it contains a concrete verifiable fact (e.g., “since 1979”, “90-day guarantee”).
- Deduplicate near-identical bullets.
- If features are empty or missing, return [].

Return ONLY JSON.
"""

## Функции для обработки данных

In [7]:
def load_checkpoint_index(
    path: Path,
    id_key: str = "parent_asin",
) -> Tuple[Set[str], Dict[str, dict]]:
    """
    Один проход по JSONL чекпоинту:
    - processed_success: asin, которые успешно обработаны (error == None)
    - latest_by_asin: последняя запись по asin (для merge при рестарте)
    """
    processed_success: Set[str] = set()
    latest_by_asin: Dict[str, dict] = {}

    if not path.exists():
        return processed_success, latest_by_asin

    with path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                obj = json.loads(line)
            except Exception:
                continue

            asin = obj.get(id_key)
            if not asin:
                continue

            latest_by_asin[asin] = obj
            if obj.get("error") is None:
                processed_success.add(asin)

    return processed_success, latest_by_asin


def append_jsonl(path: Path, obj: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a", encoding="utf-8") as f:
        f.write(json.dumps(obj, ensure_ascii=False) + "\n")


def strip_code_fences(s: str) -> str:
    s = (s or "").strip()
    if s.startswith("```"):
        s = s.split("\n", 1)[1]
        if s.endswith("```"):
            s = s[:-3]
    return s.strip()


async def clean_one(parent_asin: str, title: str, description: str, features_text: str) -> dict:
    try:
        title = (title or "").strip()
        description = (description or "").strip()
        features_text = (features_text or "").strip()

        if len(title) > MAX_TITLE_LEN:
            title = title[:MAX_TITLE_LEN]
        if len(description) > MAX_DESC_LEN:
            description = description[:MAX_DESC_LEN]
        if len(features_text) > MAX_FEATURES_LEN:
            features_text = features_text[:MAX_FEATURES_LEN]

        user_prompt = f"""TITLE:
{title}

DESCRIPTION:
{description}

FEATURES_TEXT:
{features_text}
"""
        resp = await client.chat.completions.create(
            model=MODEL,
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": user_prompt},
            ],
            temperature=0,
        )

        content = strip_code_fences(resp.choices[0].message.content or "")
        data = json.loads(content)

        feats = data.get("clean_features")
        if not isinstance(feats, list):
            feats = []
        feats = [str(x).strip() for x in feats if str(x).strip()]

        return {
            "parent_asin": parent_asin,
            "clean_title": (data.get("clean_title") or "").strip() or None,
            "clean_description": (data.get("clean_description") or "").strip() or None,
            "clean_features": feats,
            "error": None,
        }

    except Exception as e:
        return {
            "parent_asin": parent_asin,
            "clean_title": None,
            "clean_description": None,
            "clean_features": None,
            "error": f"{type(e).__name__}: {e}",
        }


async def clean_polars_df(
    df: pl.DataFrame,
    checkpoint_path: str | Path,
    id_col: str = "parent_asin",
    title_col: str = "title",
    desc_col: str = "description_text",
    features_col: str = "features_text",
    concurrency: int = 8,
) -> pl.DataFrame:
    concurrency = max(1, int(concurrency))
    checkpoint = Path(checkpoint_path)

    processed, latest_map = load_checkpoint_index(checkpoint, id_key=id_col)

    todo = df.filter(~pl.col(id_col).is_in(list(processed)))
    total = todo.height

    async def run_row(row: dict) -> dict:
        return await clean_one(
            row[id_col],
            row.get(title_col),
            row.get(desc_col),
            row.get(features_col),
        )

    new_results: list[dict] = []
    pending: list[asyncio.Task] = []

    with tqdm(total=total, desc="Cleaning items") as pbar:
        for row in todo.select([id_col, title_col, desc_col, features_col]).iter_rows(named=True):
            pending.append(asyncio.create_task(run_row(row)))

            if len(pending) >= concurrency:
                done = await asyncio.gather(*pending)
                for r in done:
                    append_jsonl(checkpoint, r)
                    new_results.append(r)
                pbar.update(len(done))
                pending.clear()

        if pending:
            done = await asyncio.gather(*pending)
            for r in done:
                append_jsonl(checkpoint, r)
                new_results.append(r)
            pbar.update(len(done))

    for r in new_results:
        asin = r.get(id_col)
        if asin:
            latest_map[asin] = r

    if latest_map:
        all_df = pl.DataFrame(list(latest_map.values()))

        for c in [id_col, "clean_title", "clean_description", "clean_features"]:
            if c not in all_df.columns:
                all_df = all_df.with_columns(pl.lit(None).alias(c))

        all_df = all_df.select([id_col, "clean_title", "clean_description", "clean_features"])

        return df.join(all_df, on=id_col, how="left")

    return df.with_columns([
        pl.lit(None).alias("clean_title"),
        pl.lit(None).alias("clean_description"),
        pl.lit(None).alias("clean_features"),
    ])

In [8]:
items_df = pl.read_parquet(INPUT_PATH)

In [9]:
items_df

shape: (63_319, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ parent_as ┆ main_cate ┆ title     ┆ average_r ┆ … ┆ price     ┆ store     ┆ categorie ┆ item_con │
│ in        ┆ gory      ┆ ---       ┆ ating     ┆   ┆ ---       ┆ ---       ┆ s_text    ┆ text     │
│ ---       ┆ ---       ┆ str       ┆ ---       ┆   ┆ f32       ┆ str       ┆ ---       ┆ ---      │
│ str       ┆ str       ┆           ┆ f32       ┆   ┆           ┆           ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ B00XJG2SL ┆ Pet       ┆ Hurtta    ┆ 4.4       ┆ … ┆ 24.950001 ┆ Hurtta    ┆ Pet       ┆ Product: │
│ G         ┆ Supplies  ┆ Pet Colle ┆           ┆   ┆           ┆           ┆ Supplies  ┆ Hurtta   │
│           ┆           ┆ ction     ┆           ┆   ┆           ┆           ┆ > Dogs >  ┆ Pet Coll │
│           ┆           ┆ 14-Inch … ┆           ┆   ┆           ┆           ┆ Collars,… ┆ ection…  │
│ B01MQTWB5 ┆ Pet       ┆ 4 Pack -  ┆ 4.4       ┆ … ┆ 15.0      ┆ Encompass ┆           ┆ Product: │
│ H         ┆ Supplies  ┆ 4 Inch    ┆           ┆   ┆           ┆ All       ┆           ┆ 4 Pack - │
│           ┆           ┆ Ring      ┆           ┆   ┆           ┆           ┆           ┆ 4 Inch   │
│           ┆           ┆ Filter    ┆           ┆   ┆           ┆           ┆           ┆ Ring …   │
│           ┆           ┆ So…       ┆           ┆   ┆           ┆           ┆           ┆          │
│ B00F3JRLY ┆ Pet       ┆ Wysong    ┆ 4.4       ┆ … ┆ 17.459999 ┆ Wysong    ┆ Pet       ┆ Product: │
│ Q         ┆ Supplies  ┆ Optimal   ┆           ┆   ┆           ┆           ┆ Supplies  ┆ Wysong   │
│           ┆           ┆ Adult     ┆           ┆   ┆           ┆           ┆ > Dogs >  ┆ Optimal  │
│           ┆           ┆ Canine    ┆           ┆   ┆           ┆           ┆ Food > D… ┆ Adult …  │
│           ┆           ┆ Fo…       ┆           ┆   ┆           ┆           ┆           ┆          │
│ B09J5FJYM ┆ Pet       ┆ Nutramax  ┆ 4.3       ┆ … ┆ 9.68      ┆ Dasuquin  ┆ Pet       ┆ Product: │
│ J         ┆ Supplies  ┆ Dasuquin  ┆           ┆   ┆           ┆           ┆ Supplies  ┆ Nutramax │
│           ┆           ┆ Joint     ┆           ┆   ┆           ┆           ┆ > Cats >  ┆ Dasuquin │
│           ┆           ┆ Health…   ┆           ┆   ┆           ┆           ┆ Health S… ┆ Joi…     │
│ B08WZ1Z9Z ┆ Pet       ┆ Batiyeer  ┆ 4.0       ┆ … ┆ null      ┆ Batiyeer  ┆ Pet       ┆ Product: │
│ F         ┆ Supplies  ┆ 4 Strings ┆           ┆   ┆           ┆           ┆ Supplies  ┆ Batiyeer │
│           ┆           ┆ in 4      ┆           ┆   ┆           ┆           ┆ > Dogs >  ┆ 4        │
│           ┆           ┆ Pieces…   ┆           ┆   ┆           ┆           ┆ Collars,… ┆ Strings  │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ in…      │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ B0013ZEGW ┆ Pet       ┆ Sera 7112 ┆ 4.6       ┆ … ┆ 20.75     ┆ Sera      ┆ Pet       ┆ Product: │
│ O         ┆ Supplies  ┆ Koi Royal ┆           ┆   ┆           ┆           ┆ Supplies  ┆ Sera     │
│           ┆           ┆ Mini 1.8  ┆           ┆   ┆           ┆           ┆ > Fish &  ┆ 7112 Koi │
│           ┆           ┆ l…        ┆           ┆   ┆           ┆           ┆ Aquatic … ┆ Royal M… │
│ B099J628C ┆           ┆ Guess     ┆ 4.6       ┆ … ┆ 10.99     ┆ Yangmics  ┆ Pet       ┆ Product: │
│ 8         ┆           ┆ What? My  ┆           ┆   ┆           ┆ Direct    ┆ Supplies  ┆ Guess    │
│           ┆           ┆ Mom is    ┆           ┆   ┆           ┆           ┆ > Dogs >  ┆ What? My │
│           ┆           ┆ Pregnant… ┆           ┆   ┆           ┆           ┆ Apparel … ┆ Mom is…  │
│ B0BJFS2B7 ┆ Pet       ┆ DIELLY 5  ┆ 4.5       ┆ … ┆ 9.88      ┆ DIELLY    ┆ Pet       ┆ Product: │
│ J         ┆ Supplies  ┆ Set AI    ┆           ┆   ┆           ┆           ┆ Supplies  ┆ DIELLY 5 │
│           ┆           ┆ Artificia ┆           ┆   ┆           ┆           ┆ > Dogs >  ┆ Set AI   │
│           ┆           ┆ l Ins…    ┆           ┆   ┆           ┆           ┆ Training… ┆ Artif…   │
│ B08DP4SF2 ┆           ┆ Downtown  ┆ 4.0       ┆ … ┆ null      ┆ Downtown  ┆ Pet       ┆ Product: │
│ 4         ┆           ┆ Pet       ┆           ┆   ┆           ┆ Pet       ┆ Supplies  ┆ Downtown │
│           ┆           ┆ Supply 3" ┆           ┆   ┆           ┆ Supply    ┆ > Dogs >  ┆ Pet      │
│           ┆           ┆ Plain B…  ┆           ┆   ┆           ┆           ┆ Treats >… ┆ Supply   │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 3…       │
│ B08DFQMJW ┆           ┆ LanYao    ┆ 4.3       ┆ … ┆ null      ┆ LanYao    ┆ Pet       ┆ Product: │
│ 6         ┆           ┆ Cat Dog   ┆           ┆   ┆           ┆           ┆ Supplies  ┆ LanYao   │
│           ┆           ┆ Bubble    ┆           ┆   ┆           ┆           ┆ > Dogs >  ┆ Cat Dog  │
│           ┆           ┆ Carrier … ┆           ┆   ┆           ┆           ┆ Carriers… ┆ Bubble…  │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [10]:
cleaned = await clean_polars_df(items_df, CHECKPOINT_PATH, concurrency=CONCURRENCY)

Cleaning items: 100%|██████████| 25398/25398 [28:32<00:00, 14.83it/s]

In [11]:
cleaned.write_parquet(OUTPUT_PATH)

In [13]:
cleaned

shape: (63_319, 14)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ parent_as ┆ main_cate ┆ title     ┆ average_r ┆ … ┆ item_cont ┆ clean_tit ┆ clean_des ┆ clean_fe │
│ in        ┆ gory      ┆ ---       ┆ ating     ┆   ┆ ext       ┆ le        ┆ cription  ┆ atures   │
│ ---       ┆ ---       ┆ str       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ str       ┆           ┆ f32       ┆   ┆ str       ┆ str       ┆ str       ┆ list[str │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ]        │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ B00XJG2SL ┆ Pet       ┆ Hurtta    ┆ 4.4       ┆ … ┆ Product:  ┆ Hurtta    ┆ Hurtta    ┆ ["Made   │
│ G         ┆ Supplies  ┆ Pet Colle ┆           ┆   ┆ Hurtta    ┆ Pet Colle ┆ harnesses ┆ from     │
│           ┆           ┆ ction     ┆           ┆   ┆ Pet Colle ┆ ction     ┆ are       ┆ durable  │
│           ┆           ┆ 14-Inch … ┆           ┆   ┆ ction…    ┆ 14-Inch … ┆ suitable  ┆ Neoprene │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ …         ┆ ",…      │
│ B01MQTWB5 ┆ Pet       ┆ 4 Pack -  ┆ 4.4       ┆ … ┆ Product:  ┆ 4 Pack -  ┆ These     ┆ ["4 pack │
│ H         ┆ Supplies  ┆ 4 Inch    ┆           ┆   ┆ 4 Pack -  ┆ 4 Inch    ┆ 4-inch    ┆ of       │
│           ┆           ┆ Ring      ┆           ┆   ┆ 4 Inch    ┆ Ring      ┆ ring      ┆ 4-inch   │
│           ┆           ┆ Filter    ┆           ┆   ┆ Ring …    ┆ Filter    ┆ filter    ┆ ring     │
│           ┆           ┆ So…       ┆           ┆   ┆           ┆ So…       ┆ socks…    ┆ filter…  │
│ B00F3JRLY ┆ Pet       ┆ Wysong    ┆ 4.4       ┆ … ┆ Product:  ┆ Wysong    ┆ Wysong    ┆ ["42%    │
│ Q         ┆ Supplies  ┆ Optimal   ┆           ┆   ┆ Wysong    ┆ Optimal   ┆ Optimal   ┆ protein  │
│           ┆           ┆ Adult     ┆           ┆   ┆ Optimal   ┆ Adult     ┆ Adult     ┆ with     │
│           ┆           ┆ Canine    ┆           ┆   ┆ Adult …   ┆ Canine    ┆ super     ┆ high     │
│           ┆           ┆ Fo…       ┆           ┆   ┆           ┆ Fo…       ┆ pre…      ┆ levels…  │
│ B09J5FJYM ┆ Pet       ┆ Nutramax  ┆ 4.3       ┆ … ┆ Product:  ┆ Nutramax  ┆ Dasuquin  ┆ ["Joint  │
│ J         ┆ Supplies  ┆ Dasuquin  ┆           ┆   ┆ Nutramax  ┆ Dasuquin  ┆ for Cats  ┆ health   │
│           ┆           ┆ Joint     ┆           ┆   ┆ Dasuquin  ┆ Joint     ┆ Soft      ┆ support  │
│           ┆           ┆ Health…   ┆           ┆   ┆ Joi…      ┆ Health…   ┆ Chews i…  ┆ for cat… │
│ B08WZ1Z9Z ┆ Pet       ┆ Batiyeer  ┆ 4.0       ┆ … ┆ Product:  ┆ Batiyeer  ┆ These     ┆ ["Made   │
│ F         ┆ Supplies  ┆ 4 Strings ┆           ┆   ┆ Batiyeer  ┆ 4 Strings ┆ collar    ┆ of       │
│           ┆           ┆ in 4      ┆           ┆   ┆ 4 Strings ┆ in 4      ┆ bells are ┆ quality  │
│           ┆           ┆ Pieces…   ┆           ┆   ┆ in…       ┆ Pieces…   ┆ made of…  ┆ brass    │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ materi…  │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ B0013ZEGW ┆ Pet       ┆ Sera 7112 ┆ 4.6       ┆ … ┆ Product:  ┆ Sera 7112 ┆ Sera Koi  ┆ ["Staple │
│ O         ┆ Supplies  ┆ Koi Royal ┆           ┆   ┆ Sera 7112 ┆ Koi Royal ┆ Royal is  ┆ food for │
│           ┆           ┆ Mini 1.8  ┆           ┆   ┆ Koi Royal ┆ Mini 1.8  ┆ a staple  ┆ Koi",    │
│           ┆           ┆ l…        ┆           ┆   ┆ M…        ┆ l…        ┆ foo…      ┆ "Stren…  │
│ B099J628C ┆           ┆ Guess     ┆ 4.6       ┆ … ┆ Product:  ┆ Pregnancy ┆ These     ┆ ["Made   │
│ 8         ┆           ┆ What? My  ┆           ┆   ┆ Guess     ┆ Announcem ┆ trendy,   ┆ from     │
│           ┆           ┆ Mom is    ┆           ┆   ┆ What? My  ┆ ent Dog   ┆ neutral   ┆ 100%     │
│           ┆           ┆ Pregnant… ┆           ┆   ┆ Mom is…   ┆ Ban…      ┆ bandanas… ┆ soft     │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ spun     │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ pol…     │
│ B0BJFS2B7 ┆ Pet       ┆ DIELLY 5  ┆ 4.5       ┆ … ┆ Product:  ┆ DieLLY 5  ┆ This dog  ┆ ["Includ │
│ J         ┆ Supplies  ┆ Set AI    ┆           ┆   ┆ DIELLY 5  ┆ Set AI    ┆ artificia ┆ es 5 AI  │
│           ┆           ┆ Artificia ┆           ┆   ┆ Set AI    ┆ Artificia ┆ l insemin ┆ rods     │
│           ┆           ┆ l Ins…    ┆           ┆   ┆ Artif…    ┆ l Ins…    ┆ ati…      ┆ tubes, 5 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ …        │
│ B08DP4SF2 ┆           ┆ Downtown  ┆ 4.0       ┆ … ┆ Product:  ┆ Downtown  ┆ Sourced,  ┆ ["Free-r │
│ 4         ┆           ┆ Pet       ┆           ┆   ┆ Downtown  ┆ Pet       ┆ inspected ┆ ange,    │
│           ┆           ┆ Supply 3" ┆           ┆   ┆ Pet       ┆ Supply 3" ┆ , and     ┆ USA gras │
│           ┆           ┆ Plain B…  ┆           ┆   ┆ Supply 3… ┆ Plain B…  ┆ packag…   ┆ s-fed    │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ bo…      │
│ B08DFQMJW ┆           ┆ LanYao    ┆ 4.3       ┆ … ┆ Product:  ┆ LanYao    ┆ This pet  ┆ ["Unique │
│ 6         ┆           ┆ Cat Dog   ┆           ┆   ┆ LanYao    ┆ Cat Dog   ┆ carrier   ┆ transpar │
│           ┆           ┆ Bubble    ┆           ┆   ┆ Cat Dog   ┆ Bubble    ┆ backpack  ┆ ent      │
│           ┆           ┆ Carrier … ┆           ┆   ┆ Bubble…   ┆ Carrier … ┆ is m…     ┆ space    │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ cap…     │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘